mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('sondage/' , include('sondage.urls')),
    path('polls/' , include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views
# Link to my index function in views.py

app_name = 'polls'

urlpatterns = [
    # ex : /polls
    path("", views.IndexView.as_view(), name="index"),
    
    #ex : details : /polls/3
    path("<int:pk>/" , views.DetailView.as_view() , name="details"),
    
    # ex results : /polls/3/results
    path("<int:pk>/results", views.ResultsView.as_view() , name="results"),
    
    # votes : /polls/3/votes
    path("<int:question_id>/votes" , views.votes ,name="votes")
]

sondage/urls.py
from django.urls import path
from . import views

app_name = "sondage"
urlpatterns = [
    path('' , views.IndexView.as_view() , name="index"),
    path('<int:pk>/' , views.QuestionDetailView.as_view() , name="details"),
    path('<int:pk>/results' , views.ResultView.as_view() , name="results"),
    path('<int:question_id>/votes' , views.votes , name="votes"),
    path('<int:question_id>/delete' , views.delete , name="delete"),
    path('add/' , views.AddQuestionView.as_view() , name="add"),
    # Add a new question in database
    path('saveQuestion' , views.addQuestion, name="saveQuestion"),
    # add choices to a question 
    path('<int:index>/addChoice' , views.addChoiceToQuestionView.as_view() , name="addChoice"),
    path('<int:question_id>/savechoice', views.savechoice , name="savechoice")
]

sondage/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    # property
    question_text = models.CharField(max_length=200)
    date_pub = models.DateTimeField("Date of publiction")
    nbvotes = models.IntegerField(default=0)
    
    def is_recent(self):
        """Verify if the question is recent. A question recent is a question posted between yesterday and now"""
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_pub <= now
    
    def __str__(self) -> str:
        return self.question_text

# Class Choice
class Choice(models.Model):
    # property
    question = models.ForeignKey(Question , on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

sondage/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.shortcuts import render , get_object_or_404
from django.views import generic
from .models import Question , Choice
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.
class IndexView(generic.ListView):
    
    template_name = "sondage/index.html"
    context_object_name = "question_lists"
    
    
    def get_queryset(self) -> QuerySet[Any]:
        return Question.objects.all().exclude(choice__isnull=True).filter(date_pub__lte=timezone.now()).order_by('-date_pub')
    

class QuestionDetailView(generic.DetailView):
    model = Question
    template_name = "sondage/details.html"
    
    
    def get_queryset(self) -> QuerySet[Any]:
        return Question.objects.filter(date_pub__lte=timezone.now())
    
    
class ResultView(generic.DetailView):
    # view the results of votes for each choice
    model = Question
    template_name = "sondage/results.html"
    
    
def votes(request , question_id):
    
    # get question who correspond to id
    question = get_object_or_404(Question , pk=question_id)
    
    # get the choice selected
    try:
        choice_selected = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError):
        # render view details sondage with ErrorMEssage
        return render(
            request, "sondage/details.html",{"question": question , "error_message":"Error, make a choice"}
        )
    else:
        choice_selected.votes += 1
        choice_selected.save()
        
        return HttpResponseRedirect(reverse("sondage:details" , args=(question_id,)))
    
   
   
class AddQuestionView(generic.ListView):
    model = Question
    template_name = "sondage/add_sondage.html"


# Add a question in database
def addQuestion(request):
    print(request.POST['question_text'])
    print(request.POST['date_pub'])
    print(request.POST['nbvotes'])
    
    # create a question occurence
    new_question = Question(question_text=request.POST['question_text'] , date_pub=request.POST['date_pub'] , nbvotes=eval(request.POST['nbvotes']))
    # save this question
    new_question.save()
    
    # get the question save in database and add the choice who correspond
    # get the index
    indexLastQuestion = len(Question.objects.all()) - 1
    print('Last index' , indexLastQuestion)
    # return HttpResponseRedirect(reverse("sondage:add"))
    return HttpResponseRedirect(reverse("sondage:addChoice" , args=(indexLastQuestion,)))
    


# Page view add a choice for a question
class addChoiceToQuestionView(generic.ListView):
    model = Question
    template_name = "sondage/add_choice.html"
    context_object_name = "question"
    # model
    
    def get_queryset(self):
        # index = self.request.GET.get('index')
        # print(index)
        # print(Question.objects.all()[len(Question.objects.all())-1].question_text)
        return Question.objects.all()[len(Question.objects.all())-1]
    

def savechoice(request , question_id):
    # get question 
    question = Question.objects.get(id = question_id)
    print("Question is :{}".format(question))
    # add choice now
    for x in range(question.nbvotes):
        print(request.POST['choice_text{}'.format(x+1)])
        question.choice_set.create(choice_text=request.POST['choice_text{}'.format(x+1)])
    
    # response redirect
    return HttpResponseRedirect(reverse("sondage:index" , args=()))

# Delete a question from Database
def delete(request , question_id):
    
    # get the question who correspond to id
    question = get_object_or_404(Question , pk=question_id)
    # delete this
    question.delete()
    # redirect to index.html
    return HttpResponseRedirect(reverse('sondage:index'))

sondage/templates/sondage/add_choice.html
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Add Choice</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'sondage/add.css' %}">
  
</head>
<body>

    <div style="font-size:18px;" id="main">    
        <h1 style="font-size:22px;">{{question.question_text}}  {{question.id}} </h1>

        {% comment %} Forms {% endcomment %}
        <form 
            action="{% url 'sondage:savechoice' question.id %}" 
            method="post"
        >
            {% csrf_token %}
            <fieldset>
                <legend>Add {{question.nbvotes}} Choices :</legend>
                {% for i in "x"|rjust:question.nbvotes %}

                    <div class="input-bloc">
                        <label>Choice {{forloop.counter}} : </label>
                        <input type="text" required="" name="choice_text{{forloop.counter}}"/>
                    </div>

                {% endfor %}
                <div class="input-bloc">
                    <input type='submit' value="Save" />
                </div> 
            </fieldset>
        </form>
    </div>
    {% comment %} <a style='text-align:center;' id="link-home" href="{% url 'sondage:index' %}">Go Home</a> {% endcomment %}
</body>

{% comment %} <script>
    let d = new Date()
    let datemin = d.toISOString().slice(0, 16);

    const myDateInput = document.getElementById('myDateInput')
    myDateInput.min = datemin
    console.log(myDateInput)
    console.log(datemin)
</script> {% endcomment %}
</html>

sondage/templates/sondage/add_sondage.html
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Add a new sondage</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'sondage/add.css' %}">
  
</head>
<body>

    <div id="main">    
        <h1>Add a new sondage</h1>

        {% comment %} Forms {% endcomment %}
        <form action="{% url 'sondage:saveQuestion' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Add a new sondage :</legend>
                <div class="input-bloc">
                    <label>Question : </label>
                    <input type="text" name="question_text"/>
                </div>

                <div class="input-bloc">
                    <label>Date publication : </label>
                    <input type="datetime-local" required id="myDateInput" name="date_pub">
                    {% comment %} <input type="date" name="date_pub"/> {% endcomment %}
                </div>

                <div class="input-bloc">
                    <label>Nombre de votes : </label>
                    <input type="number" name="nbvotes"/>
                </div>

                <div class="input-bloc">
                    <input type='submit' value="Save" />
                </div>
            </fieldset>
        </form>
    </div>
    <a style='text-align:center;' id="link-home" href="{% url 'sondage:index' %}">Go Home</a>
</body>

<script>
    let d = new Date()
    let datemin = d.toISOString().slice(0, 16);

    const myDateInput = document.getElementById('myDateInput')
    myDateInput.min = datemin
    console.log(myDateInput)
    console.log(datemin)
</script>
</html>

sondage/templates/sondage/details.html
{% load static %}
<link rel="stylesheet" href={% static 'sondage/details.css' %} />

<h1>Question : {{question.question_text}} </h1>
{% comment %} Choice {% endcomment %}
{% comment %} {% if question.choice_set.all %} {% endcomment %}

<div id="main">
    
    <form 
        action="{%url "sondage:votes" question.id %}" 
        method="post"
    >
        {% csrf_token %}
        <fieldset>
            <legend>Make your choice</legend>
            {% if error_message %}<div style="color:red;font-weight:bold;">{{error_message}}</div>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" id="choice{{choice.id}}" name="choice" value="{{choice.id}}">
                <label for="contactChoice3">{{choice.choice_text}}</label>    
            {% comment %} <li>{{choice.choice_text}}</li> {% endcomment %}
            {% endfor %}
            <br>
            <input value="Send" type="submit" />
        </fieldset>
    </form>
    <a href="{% url 'sondage:index' %}">Go to home</a>
</div>
    

sondage/templates/sondage/index.html
{% load static %} 
<link rel="stylesheet" href="{% static 'sondage/style.css' %}" />

{% if question_lists %}
<div id="header">
    <h1>Questions : </h1>
    <a href="{% url 'sondage:add' %}">Add new question</a>
</div>
<div id='main'>
    <ul>
        {% for question in question_lists %}
        <li> <a href="{%url "sondage:details" question.id %}">{{question}} </a>
            {% if question.is_recent %}(Recent) {% else %} (Not recent) {% endif %}  
            <br>
            <a href="{% url 'sondage:results' question.id %}" style="font-size:15px;">View answers</a>
            <a href="{% url 'sondage:delete' question.id %}" style="font-size:15px;">Delete</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div>
        No polls in database.
    </div>
    {% endif %}
</div>

sondage/templates/sondage/results.html
{% load static %}
<link rel="stylesheet" href="{% static 'sondage/results.css' %}" />

<div id="main">
    <h1>Results for question : <br> {{question.question_text}} </h1>
    {% comment %} Choice of question {% endcomment %}
    {% comment %} <ul> {% endcomment %}
    <div id="b-ans">
        {% for choice in question.choice_set.all %}
            <div id="ans"> {{choice.choice_text}} , votes : {{choice.votes}} </div>
        {% endfor %}
    </div>
    <a href="{% url 'sondage:index' %}" >Go home</a>
    {% comment %} </ul> {% endcomment %}
</div>