mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('sondage/' , include('sondage.urls')),
    path('polls/' , include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views
# Link to my index function in views.py

app_name = 'polls'

urlpatterns = [
    # ex : /polls
    path("", views.IndexView.as_view(), name="index"),
    
    #ex : details : /polls/3
    path("<int:pk>/" , views.DetailView.as_view() , name="details"),
    
    # ex results : /polls/3/results
    path("<int:pk>/results", views.ResultsView.as_view() , name="results"),
    
    # votes : /polls/3/votes
    path("<int:question_id>/votes" , views.votes ,name="votes")
]

polls/models.py
from django.db import models
import datetime
from django.contrib import admin
from django.db.models import CharField
from django.utils import timezone


# Create your models here.
# We have two models for polls apps : Question and Choice

class Question(models.Model):
    
    
    # Text question
    question_text = models.CharField(max_length=200)
    # Date publishing
    date_pub = models.DateTimeField("date published")
    
   
    def __str__(self) -> str:
        return self.question_text
    
    
    @admin.display(
        boolean=True,
        ordering="-date_pub",
        description="Published recently"
    )
    
    def was_published_recently(self):
        """
        the publication date is between date time now and 1 day ago
        """
        # we check if value of date_pub is between this time now - datetime.timedelta(days=1)
        # determine timezone now()
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_pub <= now


class Choice(models.Model):
    # foreign key
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # title choice
    choice_text = models.CharField(max_length=200)
    # votes count
    votes = models.IntegerField(default=0)

    def __str__(self) -> CharField:
        return self.choice_text

polls/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse , HttpResponseRedirect
from .models import Question , Choice
from django.template import loader
from django.shortcuts import render , get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.

# my first view in Django
# use now class with generic ListView for the View of my app
class IndexView(generic.ListView):
    # dont need of model
    # model = Question
    template_name = 'polls/index.html'
    context_object_name = 'join_elements'
    
    def get_queryset(self) -> QuerySet[Question]:
        """Send only past and present publications"""
        # Check with filter and with __lte (less than or equal to)
        # return Question.objects.order_by('-date_pub')[:9]
        return Question.objects.exclude(choice__isnull=True).filter(date_pub__lte=timezone.now()).order_by('-date_pub')[:9]

# Details polls
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'
    
    def get_queryset(self) -> QuerySet[Any]:
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(date_pub__lte=timezone.now())

# Results polls (/polls/4/result)
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    
    def get_queryset(self) -> QuerySet[Any]:
        return Question.objects.filter(date_pub__lte=timezone.now())

# Vote polls (/polls/5/votes)
def votes(request , question_id):
    
    # Get question correspond
    question = get_object_or_404(Question , pk = question_id)
    
    try:
        # choice selected
        choice_selected = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist): # Return message error
        return render(
            request,
            'polls/details.html',
            {'question':question, "error_message": "You didn't select a choice."}
        )
    else:
        choice_selected.votes += 1
        choice_selected.save()
        
        # Redirect with Httpresponseredirect
        return HttpResponseRedirect(reverse("polls:results" , args=(question.id,)))
    
    # return HttpResponse("Votes for polls %s"%question_id)

polls/templates/polls/details.html
{% comment %} test details html {% endcomment %}

<div style='border:solid black 1px;font-family:consolas;text-align:center;'>
    {% comment %} <h1>Question : {{question}}</h1> {% endcomment %}
    {% if question.choice_set.all %}
        {% comment %} <ul>
            {%for choice in question.choice_set.all %}
                <button style='cursor:pointer;background:black; color:white; font-family:consolas;font-size:15px;'>{{choice.choice_text}}</button>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:results' question.id %}" >Result</a> {% endcomment %}
        <a href="/polls">Go home</a>
        <form action="{% url 'polls:votes' question.id %}" method='post'>
            {% csrf_token %}
            <fieldset>
                <legend><h1> {{question.question_text}} </h1></legend>
                {% if error_message %}<p>{{ error_message }}</p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type='radio' name='choice' id="choice{{forloop.counter}}" value="{{choice.id}}" >
                    <label for="choice{{forloop.counter}}"> {{choice.choice_text}} </label>
                {% endfor %}
            </fieldset>
            <input type='submit' value='Vote' />
        </form>
    {% else %}
        <div style='border:solid 1px; text-align:center'>
            <h1> {{question.question_text}} </h1>
            No choice for this question in database
        </div>
    {% endif %}
</h1>

polls/templates/polls/index.html
<!-- {% load static %}
<link rel="stylesheet" href={% static 'polls/style.css' %} > -->

{% if join_elements %}
    <ul>
    {% for question in join_elements %}
        <li><a href="{%url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<div style='border:solid 1px; text-align:center;'>
    <h1> Answer for Question : {{question.question_text}} </h1>
    {% if question.choice_set.all %}
        <ul style='list-style:none'>
            {% for choice in question.choice_set.all %}
            <li>{{ choice }} , votes : {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:details' question.id %}">Votez again ?</a>
    {% else %}
    <div>
        No choice in database
    </div>
    {% endif %}
</div>